# Generated by Django 5.2.17 on 2026-08-20 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freight', '0001_initial'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierLoadCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_candidacies', to='freight.carrier')),
                ('current_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_candidates', to='inquiries.carrierquote')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_candidacies', to='freight.load')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_version', models.CharField(max_length=100)),
                ('pickup_date_used', models.DateField()),
                ('authority_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable')], max_length=15)),
                ('safety_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable')], max_length=15)),
                ('insurance_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable')], max_length=15)),
                ('overall_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('needs_review', 'Needs Review')], max_length=15)),
                ('carrier_facts_snapshot', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_assessments', to='candidates.carrierloadcandidate')),
                ('triggering_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_compliance_assessments', to='inquiries.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carrierloadcandidate',
            name='current_compliance_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_candidates', to='candidates.complianceassessment'),
        ),
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy_version', models.CharField(max_length=100)),
                ('identity_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable')], max_length=15)),
                ('equipment_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable')], max_length=15)),
                ('availability_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable')], max_length=15)),
                ('onboarding_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('not_applicable', 'Not Applicable')], max_length=15)),
                ('final_status', models.CharField(choices=[('blocked', 'Blocked'), ('needs_compliance_review', 'Needs Compliance Review'), ('needs_clarification', 'Needs Clarification'), ('needs_onboarding', 'Needs Onboarding'), ('eligible', 'Eligible')], max_length=25)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_assessments', to='candidates.carrierloadcandidate')),
                ('compliance_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_assessments', to='candidates.complianceassessment')),
                ('triggering_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_eligibility_assessments', to='inquiries.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carrierloadcandidate',
            name='current_eligibility_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_candidates', to='candidates.eligibilityassessment'),
        ),
        migrations.CreateModel(
            name='CandidateAssessmentReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.CharField(choices=[('authority', 'Authority'), ('safety', 'Safety'), ('insurance', 'Insurance'), ('identity', 'Identity'), ('equipment', 'Equipment'), ('availability', 'Availability'), ('onboarding', 'Onboarding'), ('quote', 'Quote')], max_length=15)),
                ('code', models.CharField(choices=[('authority_inactive', 'Authority Inactive'), ('authority_unknown', 'Authority Unknown'), ('safety_unacceptable', 'Safety Unacceptable'), ('safety_unknown', 'Safety Unknown'), ('insurance_expired', 'Insurance Expired'), ('insurance_expiry_unknown', 'Insurance Expiry Unknown'), ('equipment_mismatch', 'Equipment Mismatch'), ('equipment_unknown', 'Equipment Unknown'), ('equipment_conflicting', 'Equipment Conflicting'), ('carrier_unavailable', 'Carrier Unavailable'), ('availability_unknown', 'Availability Unknown'), ('availability_conditional', 'Availability Conditional'), ('availability_conflicting', 'Availability Conflicting'), ('carrier_not_onboarded', 'Carrier Not Onboarded'), ('quote_missing', 'Quote Missing'), ('quote_ambiguous', 'Quote Ambiguous')], max_length=30)),
                ('severity', models.CharField(choices=[('blocker', 'Blocker'), ('review', 'Review'), ('warning', 'Warning'), ('information', 'Information')], max_length=15)),
                ('observed_value', models.CharField(blank=True, max_length=200, null=True)),
                ('required_value', models.CharField(blank=True, max_length=200, null=True)),
                ('stable_evidence_id', models.CharField(blank=True, max_length=300, null=True)),
                ('details', models.TextField(blank=True, default='')),
                ('eligibility_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='candidates.eligibilityassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.CharField(choices=[('supporting', 'Supporting'), ('superseding', 'Superseding'), ('conflicting', 'Conflicting')], max_length=15)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_links', to='inquiries.inquiry')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_inquiries', to='candidates.carrierloadcandidate')),
            ],
            options={
                'verbose_name_plural': 'candidate inquiries',
                'constraints': [models.UniqueConstraint(fields=('candidate', 'inquiry'), name='candidates_inquiry_link_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='carrierloadcandidate',
            constraint=models.UniqueConstraint(fields=('carrier', 'load'), name='candidates_carrier_load_uniq'),
        ),
    ]
