# Generated by Django 5.2.17 on 2026-08-20 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityassessment',
            name='triggering_review_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_eligibility_assessments', to='workspace.inquiryreviewaction'),
        ),
        migrations.AddField(
            model_name='carrierloadcandidate',
            name='current_eligibility_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_candidates', to='candidates.eligibilityassessment'),
        ),
        migrations.AddField(
            model_name='candidateassessmentreason',
            name='eligibility_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='candidates.eligibilityassessment'),
        ),
        migrations.AddConstraint(
            model_name='candidateinquiry',
            constraint=models.UniqueConstraint(fields=('candidate', 'inquiry'), name='candidates_inquiry_link_uniq'),
        ),
        migrations.AddConstraint(
            model_name='complianceassessment',
            constraint=models.CheckConstraint(condition=models.Q(('authority_result__in', ['pass', 'fail', 'unknown', 'not_applicable']), ('safety_result__in', ['pass', 'fail', 'unknown', 'not_applicable']), ('insurance_result__in', ['pass', 'fail', 'unknown', 'not_applicable']), ('overall_result__in', ['pass', 'fail', 'needs_review'])), name='candidates_compliance_vocab'),
        ),
        migrations.AddConstraint(
            model_name='eligibilityassessment',
            constraint=models.CheckConstraint(condition=models.Q(('identity_result__in', ['pass', 'fail', 'unknown', 'not_applicable']), ('equipment_result__in', ['pass', 'fail', 'unknown', 'not_applicable']), ('availability_result__in', ['pass', 'fail', 'unknown', 'not_applicable']), ('onboarding_result__in', ['pass', 'fail', 'unknown', 'not_applicable']), ('final_status__in', ['blocked', 'needs_compliance_review', 'needs_clarification', 'needs_onboarding', 'eligible'])), name='candidates_eligibility_vocab'),
        ),
        migrations.AddConstraint(
            model_name='carrierloadcandidate',
            constraint=models.UniqueConstraint(fields=('carrier', 'load'), name='candidates_carrier_load_uniq'),
        ),
    ]
