# Generated by Django 5.2.17 on 2026-08-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityassessment',
            name='triggering_review_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_eligibility_assessments', to='workspace.inquiryreviewaction'),
        ),
    ]
