# Generated by Django 5.2.17 on 2026-08-20 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('dataset_version', models.CharField(max_length=100)),
                ('dataset_checksum', models.CharField(max_length=64)),
                ('git_commit_sha', models.CharField(max_length=40)),
                ('prompt_versions', models.JSONField(blank=True, default=dict)),
                ('model_versions', models.JSONField(blank=True, default=dict)),
                ('policy_version', models.CharField(blank=True, max_length=100, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('langfuse_dataset_run_id', models.CharField(blank=True, max_length=200, null=True)),
                ('cases_total', models.IntegerField(blank=True, null=True)),
                ('cases_passed', models.IntegerField(blank=True, null=True)),
                ('cases_failed', models.IntegerField(blank=True, null=True)),
                ('cases_errored', models.IntegerField(blank=True, null=True)),
                ('aggregate_metrics', models.JSONField(blank=True, default=dict)),
                ('evaluation_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('report_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('transcription', 'Transcription'), ('extraction', 'Extraction'), ('draft', 'Draft'), ('assistant_turn', 'Assistant Turn'), ('evaluation_case', 'Evaluation Case')], max_length=20)),
                ('usage_category', models.CharField(choices=[('ingestion', 'Ingestion'), ('assistant', 'Assistant'), ('drafting', 'Drafting'), ('evaluation', 'Evaluation')], max_length=15)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=15)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('provider_call_count', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('audio_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_error_summary', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['operation_type', 'status'], name='aiops_aiope_operati_f2ef6f_idx'), models.Index(fields=['usage_category'], name='aiops_aiope_usage_c_467c63_idx'), models.Index(fields=['correlation_id'], name='aiops_aiope_correla_7e3071_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCaseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.CharField(max_length=200)),
                ('stable_source_id', models.CharField(max_length=200)),
                ('case_type', models.CharField(choices=[('email', 'Email'), ('call', 'Call')], max_length=10)),
                ('evaluation_mode', models.CharField(blank=True, choices=[('reviewed_transcript', 'Reviewed Transcript'), ('end_to_end', 'End To End')], max_length=25, null=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('errored', 'Errored')], max_length=10)),
                ('expected_label_ref', models.CharField(max_length=500)),
                ('actual_output', models.JSONField(blank=True, default=dict)),
                ('langfuse_trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('failure_categories', models.JSONField(blank=True, default=list)),
                ('failure_analysis', models.TextField(blank=True, default='')),
                ('suggested_improvement', models.TextField(blank=True, default='')),
                ('ai_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_cases', to='aiops.aioperation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='aiops.evaluationrun')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('evaluator_type', models.CharField(choices=[('deterministic', 'Deterministic'), ('llm_judge', 'Llm Judge'), ('human', 'Human')], max_length=15)),
                ('numeric_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('categorical_score', models.CharField(blank=True, max_length=100, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('case_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='aiops.evaluationcaseresult')),
            ],
        ),
        migrations.CreateModel(
            name='AIProviderCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField()),
                ('provider', models.CharField(choices=[('openai', 'Openai'), ('deepgram', 'Deepgram')], max_length=20)),
                ('operation_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('provider_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=50, null=True)),
                ('prompt_source', models.CharField(blank=True, choices=[('langfuse', 'Langfuse'), ('cache', 'Cache'), ('local_fallback', 'Local Fallback')], max_length=20, null=True)),
                ('langfuse_trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('langfuse_observation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=15)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('audio_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('pricing_version', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_calls', to='aiops.aioperation')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status'], name='aiops_aipro_provide_8b293a_idx')],
                'constraints': [models.UniqueConstraint(fields=('operation', 'sequence'), name='aiops_provider_call_sequence_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationcaseresult',
            constraint=models.UniqueConstraint(fields=('run', 'case_id'), name='aiops_evaluation_case_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationscore',
            constraint=models.CheckConstraint(condition=models.Q(('numeric_score__isnull', False), ('categorical_score__isnull', False), _connector='OR'), name='aiops_score_has_a_value'),
        ),
    ]
