# Generated by Django 5.2.17 on 2026-08-20 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('as_of_at', models.DateTimeField()),
                ('display_timezone', models.CharField(default='America/New_York', max_length=64)),
                ('manifest_checksum', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='freight_one_active_snapshot'), models.UniqueConstraint(fields=('version', 'manifest_checksum'), name='freight_snapshot_version_checksum_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('loads', 'Loads'), ('carriers', 'Carriers'), ('emails', 'Emails'), ('calls', 'Calls'), ('market_rates', 'Market Rates')], max_length=20)),
                ('source_filename', models.CharField(max_length=255)),
                ('content_checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('partially_failed', 'Partially Failed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_existing', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('dataset_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='freight.datasetsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_identifier', models.CharField(max_length=100)),
                ('mc_number_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('mc_number_normalized', models.CharField(blank=True, max_length=50, null=True)),
                ('dot_number_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('dot_number_normalized', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('home_base_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('factoring_company', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_terms_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('reliability_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('loads_completed_with_goodlane', models.IntegerField(blank=True, null=True)),
                ('avg_response_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('authority_status', models.CharField(blank=True, max_length=50, null=True)),
                ('safety_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('onboarded', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('dataset_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carriers', to='freight.datasetsnapshot')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carriers', to='freight.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_state', models.CharField(max_length=2)),
                ('destination_state', models.CharField(max_length=2)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('origin_state', 'destination_state'), name='freight_lane_directional_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CarrierPreferredLane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_lanes', to='freight.carrier')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_preferences', to='freight.lane')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_load_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('covered', 'Covered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_state', models.CharField(max_length=2)),
                ('origin_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(max_length=2)),
                ('destination_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('distance_miles', models.IntegerField(blank=True, null=True)),
                ('equipment_type_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_lbs', models.IntegerField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_window_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_start_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_end_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_window_status', models.CharField(choices=[('range', 'Range'), ('single_time', 'Single Time'), ('qualitative', 'Qualitative'), ('missing', 'Missing'), ('invalid', 'Invalid')], max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('offered_rate_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipper_name', models.CharField(blank=True, max_length=200, null=True)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('dataset_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='freight.datasetsnapshot')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='freight.equipmenttype')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='freight.importbatch')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='freight.lane')),
            ],
        ),
        migrations.CreateModel(
            name='MarketRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week_start', models.DateField()),
                ('average_rate_per_mile', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_rate_per_mile', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_rate_per_mile', models.DecimalField(decimal_places=2, max_digits=8)),
                ('load_volume', models.IntegerField()),
                ('dataset_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_rates', to='freight.datasetsnapshot')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_rates', to='freight.equipmenttype')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_rates', to='freight.importbatch')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_rates', to='freight.lane')),
            ],
            options={
                'verbose_name_plural': 'market rate history',
            },
        ),
        migrations.CreateModel(
            name='CarrierContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email_raw', models.CharField(blank=True, max_length=254, null=True)),
                ('email_normalized', models.CharField(blank=True, max_length=254, null=True)),
                ('phone_raw', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_normalized', models.CharField(blank=True, max_length=50, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='freight.carrier')),
            ],
            options={
                'indexes': [models.Index(fields=['email_normalized'], name='freight_car_email_n_76f9b0_idx'), models.Index(fields=['phone_normalized'], name='freight_car_phone_n_fead99_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('carrier',), name='freight_one_primary_contact_per_carrier')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=50)),
                ('raw_label', models.CharField(max_length=100)),
                ('normalized_label', models.CharField(max_length=100)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='freight.equipmenttype')),
            ],
            options={
                'verbose_name_plural': 'equipment aliases',
                'constraints': [models.UniqueConstraint(fields=('source', 'normalized_label'), name='freight_equipment_alias_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CarrierEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='freight.carrier')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_equipment', to='freight.equipmenttype')),
            ],
            options={
                'verbose_name_plural': 'carrier equipment',
                'constraints': [models.UniqueConstraint(fields=('carrier', 'equipment_type'), name='freight_carrier_equipment_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('dataset_snapshot', 'source_type', 'source_filename', 'content_checksum'), name='freight_import_batch_idempotency_uniq'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['mc_number_normalized'], name='freight_car_mc_numb_80a07d_idx'),
        ),
        migrations.AddIndex(
            model_name='carrier',
            index=models.Index(fields=['dot_number_normalized'], name='freight_car_dot_num_fa091d_idx'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(fields=('dataset_snapshot', 'source_identifier'), name='freight_carrier_source_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(condition=models.Q(('mc_number_normalized__isnull', False)), fields=('dataset_snapshot', 'mc_number_normalized'), name='freight_carrier_mc_uniq_when_present'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.UniqueConstraint(condition=models.Q(('dot_number_normalized__isnull', False)), fields=('dataset_snapshot', 'dot_number_normalized'), name='freight_carrier_dot_uniq_when_present'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.CheckConstraint(condition=models.Q(('reliability_score__isnull', True), models.Q(('reliability_score__gte', 0), ('reliability_score__lte', 5)), _connector='OR'), name='freight_carrier_reliability_scale'),
        ),
        migrations.AddConstraint(
            model_name='carrier',
            constraint=models.CheckConstraint(condition=models.Q(('loads_completed_with_goodlane__isnull', True), ('loads_completed_with_goodlane__gte', 0), _connector='OR'), name='freight_carrier_loads_completed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='carrierpreferredlane',
            constraint=models.UniqueConstraint(fields=('carrier', 'lane'), name='freight_carrier_preferred_lane_uniq'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['status'], name='freight_loa_status_a5c69e_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['pickup_date'], name='freight_loa_pickup__2e3969_idx'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.UniqueConstraint(fields=('dataset_snapshot', 'external_load_id'), name='freight_load_external_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.CheckConstraint(condition=models.Q(('distance_miles__isnull', True), ('distance_miles__gt', 0), _connector='OR'), name='freight_load_distance_positive'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.CheckConstraint(condition=models.Q(('weight_lbs__isnull', True), ('weight_lbs__gte', 0), _connector='OR'), name='freight_load_weight_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='load',
            constraint=models.CheckConstraint(condition=models.Q(('offered_rate_usd__isnull', True), ('offered_rate_usd__gte', 0), _connector='OR'), name='freight_load_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='marketratehistory',
            constraint=models.UniqueConstraint(fields=('dataset_snapshot', 'week_start', 'lane', 'equipment_type'), name='freight_market_rate_week_uniq'),
        ),
        migrations.AddConstraint(
            model_name='marketratehistory',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_rate_per_mile__lte', models.F('average_rate_per_mile')), ('average_rate_per_mile__lte', models.F('maximum_rate_per_mile'))), name='freight_market_rate_band_ordering'),
        ),
        migrations.AddConstraint(
            model_name='marketratehistory',
            constraint=models.CheckConstraint(condition=models.Q(('load_volume__gte', 0)), name='freight_market_rate_volume_non_negative'),
        ),
    ]
