# Generated by Django 5.2.17 on 2026-08-20 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aiops', '0001_initial'),
        ('comms', '0001_initial'),
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_part', models.CharField(choices=[('subject', 'Subject'), ('body', 'Body'), ('transcript', 'Transcript')], max_length=15)),
                ('stable_evidence_id', models.CharField(max_length=300)),
                ('excerpt', models.TextField()),
                ('start_offset', models.IntegerField(blank=True, null=True)),
                ('end_offset', models.IntegerField(blank=True, null=True)),
                ('start_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('end_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('communication_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_spans', to='comms.communicationevent')),
                ('transcript_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_spans', to='comms.transcriptsegment')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_generation', models.PositiveIntegerField()),
                ('schema_version', models.CharField(max_length=50)),
                ('prompt_name', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=50)),
                ('prompt_source', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(max_length=100)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('validated_output', models.JSONField(blank=True, null=True)),
                ('validation_status', models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid', 'Invalid')], max_length=10, null=True)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('ai_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='aiops.aioperation')),
                ('communication_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='comms.communicationevent')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='comms.ingestionjob')),
                ('transcript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='comms.transcript')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('primary_intent', models.CharField(choices=[('availability', 'Availability'), ('rate_quote', 'Rate Quote'), ('rate_negotiation', 'Rate Negotiation'), ('load_detail_question', 'Load Detail Question'), ('compliance', 'Compliance'), ('confirmation', 'Confirmation'), ('decline', 'Decline'), ('factoring_or_payment', 'Factoring Or Payment'), ('problem_or_exception', 'Problem Or Exception'), ('general_inquiry', 'General Inquiry'), ('other', 'Other')], max_length=25)),
                ('availability_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('conditional', 'Conditional'), ('unavailable', 'Unavailable'), ('not_stated', 'Not Stated'), ('conflicting', 'Conflicting')], default='not_stated', max_length=15)),
                ('equipment_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_resolution_status', models.CharField(choices=[('verified', 'Verified'), ('needs_review', 'Needs Review'), ('unmatched', 'Unmatched')], default='unmatched', max_length=15)),
                ('load_resolution_status', models.CharField(choices=[('verified', 'Verified'), ('needs_review', 'Needs Review'), ('unmatched', 'Unmatched')], default='unmatched', max_length=15)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='unreviewed', max_length=15)),
                ('summary', models.TextField(blank=True, default='')),
                ('conditions_text', models.TextField(blank=True, default='')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='freight.carrier')),
                ('communication_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='comms.communicationevent')),
                ('current_extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canonical_inquiries', to='inquiries.extractionrun')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='freight.equipmenttype')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='freight.load')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
            },
        ),
        migrations.CreateModel(
            name='CarrierQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('quote_type', models.CharField(choices=[('carrier_quote', 'Carrier Quote'), ('carrier_counteroffer', 'Carrier Counteroffer'), ('broker_rate_reference', 'Broker Rate Reference'), ('accepted_broker_rate', 'Accepted Broker Rate'), ('ambiguous', 'Ambiguous')], max_length=25)),
                ('rate_basis', models.CharField(choices=[('all_in', 'All In'), ('per_mile', 'Per Mile'), ('hourly', 'Hourly'), ('unknown', 'Unknown')], max_length=10)),
                ('is_current', models.BooleanField(default=False)),
                ('evidence_status', models.CharField(choices=[('explicit', 'Explicit'), ('inferred', 'Inferred'), ('missing', 'Missing'), ('conflicting', 'Conflicting')], max_length=15)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='inquiries.carrierquote')),
                ('evidence_spans', models.ManyToManyField(blank=True, related_name='quotes', to='inquiries.evidencespan')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='inquiries.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryCarrierMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_tier', models.CharField(choices=[('exact', 'Exact'), ('strong', 'Strong'), ('weak', 'Weak'), ('conflicting', 'Conflicting')], max_length=15)),
                ('primary_method', models.CharField(choices=[('mc_number', 'Mc Number'), ('dot_number', 'Dot Number'), ('email', 'Email'), ('phone', 'Phone'), ('multi_signal', 'Multi Signal'), ('name_similarity', 'Name Similarity')], max_length=20)),
                ('signal_codes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='proposed', max_length=10)),
                ('is_selected', models.BooleanField(default=False)),
                ('selection_source', models.CharField(blank=True, choices=[('deterministic', 'Deterministic'), ('broker', 'Broker')], max_length=15, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_matches', to='freight.carrier')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_matches', to='inquiries.inquiry')),
            ],
            options={
                'verbose_name_plural': 'inquiry carrier matches',
            },
        ),
        migrations.CreateModel(
            name='InquiryFieldAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(choices=[('carrier_identity', 'Carrier Identity'), ('load_reference', 'Load Reference'), ('equipment', 'Equipment'), ('availability', 'Availability'), ('intent', 'Intent'), ('rate', 'Rate'), ('question', 'Question'), ('conditions', 'Conditions')], max_length=20)),
                ('evidence_status', models.CharField(choices=[('explicit', 'Explicit'), ('inferred', 'Inferred'), ('missing', 'Missing'), ('conflicting', 'Conflicting')], max_length=15)),
                ('value_snapshot', models.JSONField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_current', models.BooleanField(default=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_assessments', to='inquiries.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryFieldEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.CharField(choices=[('supporting', 'Supporting'), ('contradicting', 'Contradicting')], max_length=15)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='inquiries.inquiryfieldassessment')),
                ('evidence_span', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_links', to='inquiries.evidencespan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.CharField(choices=[('availability', 'Availability'), ('rate_quote', 'Rate Quote'), ('rate_negotiation', 'Rate Negotiation'), ('load_detail_question', 'Load Detail Question'), ('compliance', 'Compliance'), ('confirmation', 'Confirmation'), ('decline', 'Decline'), ('factoring_or_payment', 'Factoring Or Payment'), ('problem_or_exception', 'Problem Or Exception'), ('general_inquiry', 'General Inquiry'), ('other', 'Other')], max_length=25)),
                ('is_primary', models.BooleanField(default=False)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='inquiries.inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='InquiryLoadMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_tier', models.CharField(choices=[('exact', 'Exact'), ('strong', 'Strong'), ('weak', 'Weak'), ('conflicting', 'Conflicting')], max_length=15)),
                ('primary_method', models.CharField(choices=[('external_load_id', 'External Load Id'), ('corrected_reference', 'Corrected Reference'), ('lane_equipment_pickup', 'Lane Equipment Pickup'), ('lane_or_equipment', 'Lane Or Equipment')], max_length=25)),
                ('signal_codes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='proposed', max_length=10)),
                ('is_selected', models.BooleanField(default=False)),
                ('selection_source', models.CharField(blank=True, choices=[('deterministic', 'Deterministic'), ('broker', 'Broker')], max_length=15, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_matches', to='inquiries.inquiry')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_matches', to='freight.load')),
            ],
            options={
                'verbose_name_plural': 'inquiry load matches',
            },
        ),
        migrations.CreateModel(
            name='InquiryQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('rate', 'Rate'), ('weight', 'Weight'), ('pickup_window', 'Pickup Window'), ('delivery', 'Delivery'), ('equipment', 'Equipment'), ('load_details', 'Load Details'), ('compliance', 'Compliance'), ('next_steps', 'Next Steps'), ('other', 'Other')], max_length=20)),
                ('question_text', models.TextField()),
                ('answer_status', models.CharField(choices=[('unanswered', 'Unanswered'), ('answered', 'Answered')], default='unanswered', max_length=15)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='inquiries.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryReviewReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(choices=[('missing_mc', 'Missing Mc'), ('garbled_mc', 'Garbled Mc'), ('weak_carrier_match', 'Weak Carrier Match'), ('conflicting_carrier_identity', 'Conflicting Carrier Identity'), ('ambiguous_load_reference', 'Ambiguous Load Reference'), ('conflicting_load_reference', 'Conflicting Load Reference'), ('equipment_conflict', 'Equipment Conflict'), ('ambiguous_rate', 'Ambiguous Rate'), ('missing_rate', 'Missing Rate'), ('conflicting_availability', 'Conflicting Availability'), ('low_confidence_transcript_evidence', 'Low Confidence Transcript Evidence'), ('quote_chronology_unresolved', 'Quote Chronology Unresolved'), ('metadata_content_conflict', 'Metadata Content Conflict'), ('extraction_validation_failure', 'Extraction Validation Failure')], max_length=40)),
                ('severity', models.CharField(choices=[('review', 'Review'), ('informational', 'Informational')], default='review', max_length=15)),
                ('details', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('field_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_reasons', to='inquiries.inquiryfieldassessment')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reasons', to='inquiries.inquiry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='evidencespan',
            index=models.Index(fields=['stable_evidence_id'], name='inquiries_e_stable__d05f62_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencespan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_part__in', ['subject', 'body']), ('start_offset__isnull', False), ('end_offset__isnull', False), ('start_seconds__isnull', True), ('end_seconds__isnull', True), ('transcript_segment__isnull', True)), models.Q(('source_part', 'transcript'), ('start_seconds__isnull', False), ('end_seconds__isnull', False), ('start_offset__isnull', True), ('end_offset__isnull', True)), _connector='OR'), name='inquiries_span_channel_shape'),
        ),
        migrations.AddConstraint(
            model_name='evidencespan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('start_offset__isnull', True), ('end_offset__gte', models.F('start_offset')), _connector='OR'), models.Q(('start_seconds__isnull', True), ('end_seconds__gte', models.F('start_seconds')), _connector='OR')), name='inquiries_span_ordering'),
        ),
        migrations.AddConstraint(
            model_name='evidencespan',
            constraint=models.UniqueConstraint(fields=('communication_event', 'stable_evidence_id'), name='inquiries_span_stable_id_uniq'),
        ),
        migrations.AddIndex(
            model_name='extractionrun',
            index=models.Index(fields=['communication_event', 'schema_version', 'prompt_version', 'model'], name='inquiries_extraction_reuse_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('communication_event',), name='inquiries_one_current_extraction_per_event'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['review_status'], name='inquiries_i_review__ee3328_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['primary_intent'], name='inquiries_i_primary_62c9c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(fields=('communication_event', 'sequence_number'), name='inquiries_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['unreviewed', 'needs_review', 'approved', 'rejected'])), name='inquiries_review_status_vocab'),
        ),
        migrations.AddConstraint(
            model_name='carrierquote',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='inquiries_quote_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inquirycarriermatch',
            constraint=models.UniqueConstraint(fields=('inquiry', 'carrier'), name='inquiries_carrier_candidate_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inquirycarriermatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('inquiry',), name='inquiries_one_selected_carrier'),
        ),
        migrations.AddConstraint(
            model_name='inquiryfieldassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('inquiry', 'field_name'), name='inquiries_one_current_assessment_per_field'),
        ),
        migrations.AddConstraint(
            model_name='inquiryintent',
            constraint=models.UniqueConstraint(fields=('inquiry', 'intent'), name='inquiries_intent_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inquiryintent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('inquiry',), name='inquiries_one_primary_intent'),
        ),
        migrations.AddConstraint(
            model_name='inquiryloadmatch',
            constraint=models.UniqueConstraint(fields=('inquiry', 'load'), name='inquiries_load_candidate_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inquiryloadmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_selected', True)), fields=('inquiry',), name='inquiries_one_selected_load'),
        ),
    ]
