# Generated by Django 5.2.17 on 2026-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirycarriermatch',
            name='primary_method',
            field=models.CharField(choices=[('mc_number', 'Mc Number'), ('dot_number', 'Dot Number'), ('email', 'Email'), ('phone', 'Phone'), ('multi_signal', 'Multi Signal'), ('name_similarity', 'Name Similarity'), ('broker_confirmed', 'Broker Confirmed')], max_length=20),
        ),
    ]
