# Generated by Django 5.2.17 on 2026-08-20 07:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('call', 'Call')], max_length=10)),
                ('origin', models.CharField(choices=[('dataset', 'Dataset'), ('manual', 'Manual'), ('simulation', 'Simulation')], max_length=15)),
                ('external_source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stable_evidence_id', models.CharField(max_length=200, unique=True)),
                ('source_timestamp_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('source_timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_fingerprint', models.CharField(max_length=64, unique=True)),
                ('dataset_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_events', to='freight.datasetsnapshot')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_events', to='freight.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.BigIntegerField()),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('audio_format', models.CharField(max_length=20)),
                ('sample_rate', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('communication_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_recording', to='comms.communicationevent')),
            ],
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_email_raw', models.CharField(max_length=254)),
                ('sender_email_normalized', models.CharField(max_length=254)),
                ('sender_name', models.CharField(blank=True, default='', max_length=200)),
                ('recipient_raw', models.CharField(blank=True, max_length=254, null=True)),
                ('recipient_normalized', models.CharField(blank=True, max_length=254, null=True)),
                ('subject', models.TextField(blank=True, default='')),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('communication_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_content', to='comms.communicationevent')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('dataset', 'Dataset'), ('manual', 'Manual'), ('simulation', 'Simulation')], max_length=15)),
                ('source_type', models.CharField(choices=[('email', 'Email'), ('call', 'Call')], max_length=10)),
                ('submitted_by', models.CharField(blank=True, max_length=200, null=True)),
                ('suspected_load_reference_raw', models.CharField(blank=True, max_length=100, null=True)),
                ('suspected_carrier_identity_raw', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='queued', max_length=15)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('last_error_summary', models.TextField(blank=True, default='')),
                ('communication_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_job', to='comms.communicationevent')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to='freight.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_generation', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('requested_model', models.CharField(max_length=100)),
                ('requested_options', models.JSONField(blank=True, default=dict)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('provider_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_text', models.TextField()),
                ('normalized_text', models.TextField()),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=False)),
                ('call_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='comms.callrecording')),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='comms.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField()),
                ('speaker_label', models.CharField(blank=True, default='', max_length=50)),
                ('speaker_role', models.CharField(blank=True, choices=[('broker', 'Broker'), ('carrier', 'Carrier')], max_length=10, null=True)),
                ('start_seconds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('end_seconds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('text', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='comms.transcript')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['occurred_at'], name='comms_commu_occurre_7df1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['channel', 'origin'], name='comms_commu_channel_2cf91d_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'dataset'), ('external_source_id__isnull', False)), fields=('dataset_snapshot', 'external_source_id'), name='comms_dataset_event_source_id_uniq'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['sha256_checksum'], name='comms_callr_sha256__3cf6db_idx'),
        ),
        migrations.AddIndex(
            model_name='emailcontent',
            index=models.Index(fields=['sender_email_normalized'], name='comms_email_sender__598728_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['status'], name='comms_inges_status_700071_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['content_fingerprint'], name='comms_inges_content_c9c29f_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('call_recording',), name='comms_one_current_transcript_per_recording'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(fields=('transcript', 'sequence'), name='comms_transcript_segment_sequence_uniq'),
        ),
    ]
