# Generated by Django 5.2.17 on 2026-08-20 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aiops', '0001_initial'),
        ('candidates', '0001_initial'),
        ('freight', '0001_initial'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('load', 'Load')], max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant_conversations', to='freight.load')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workspace.assistantconversation')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='AssistantCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('transcript_segment', 'Transcript Segment'), ('load', 'Load'), ('carrier', 'Carrier'), ('quote', 'Quote'), ('assessment', 'Assessment'), ('market_rate', 'Market Rate')], max_length=20)),
                ('stable_source_id', models.CharField(max_length=300)),
                ('display_label', models.CharField(max_length=300)),
                ('evidence_span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant_citations', to='inquiries.evidencespan')),
                ('assistant_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='workspace.assistantmessage')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='AssistantRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed Out')], default='running', max_length=10)),
                ('scope_snapshot', models.JSONField(blank=True, default=dict)),
                ('prompt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('langfuse_trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('ai_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant_runs', to='aiops.aioperation')),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_assistant_message', to='workspace.assistantmessage')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workspace.assistantconversation')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs_as_user_message', to='workspace.assistantmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_type', models.CharField(choices=[('provide_rate', 'Provide Rate'), ('negotiate_rate', 'Negotiate Rate'), ('request_information', 'Request Information'), ('confirm_next_steps', 'Confirm Next Steps'), ('decline', 'Decline'), ('defer', 'Defer')], max_length=25)),
                ('generated_subject', models.TextField(blank=True, default='')),
                ('generated_body', models.TextField()),
                ('current_subject', models.TextField(blank=True, default='')),
                ('current_body', models.TextField()),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('edited', 'Edited'), ('copied', 'Copied'), ('discarded', 'Discarded')], default='generated', max_length=15)),
                ('created_by', models.CharField(max_length=200)),
                ('prompt_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('langfuse_trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('copied_at', models.DateTimeField(blank=True, null=True)),
                ('ai_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='aiops.aioperation')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='candidates.carrierloadcandidate')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='freight.carrier')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='inquiries.inquiry')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='freight.load')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(blank=True, max_length=30, null=True)),
                ('stable_source_id', models.CharField(blank=True, max_length=300, null=True)),
                ('fact_name', models.CharField(max_length=100)),
                ('fact_value', models.JSONField(blank=True, null=True)),
                ('evidence_span', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_links', to='inquiries.evidencespan')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='workspace.draftresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InquiryReviewAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('approve_extraction', 'Approve Extraction'), ('reject_extraction', 'Reject Extraction'), ('correct_carrier', 'Correct Carrier'), ('correct_load', 'Correct Load'), ('reopen_review', 'Reopen Review')], max_length=25)),
                ('actor_label', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='inquiries.inquiry')),
                ('new_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='freight.carrier')),
                ('new_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='freight.load')),
                ('previous_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='freight.carrier')),
                ('previous_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='freight.load')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField()),
                ('tool_name', models.CharField(max_length=100)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('result_record_ids', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('assistant_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='workspace.assistantrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assistantmessage',
            constraint=models.UniqueConstraint(fields=('conversation', 'sequence'), name='workspace_message_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='assistantcitation',
            constraint=models.UniqueConstraint(fields=('assistant_message', 'sequence'), name='workspace_citation_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='toolexecution',
            constraint=models.UniqueConstraint(fields=('assistant_run', 'sequence'), name='workspace_tool_sequence_uniq'),
        ),
    ]
